### ISSUE TITLE
FCSWatch Hook Documentation 

### ISSUE THREAD

**Issue by tylerhartwig** [humhei/FCSWatch#18]
I saw [here](https://github.com/Microsoft/visualfsharp/issues/6484#issuecomment-481815718) that FCSWatch is supposed to support web hooks now, and sends over the compilation results.

Is this true? If so, what is the syntax for using this? Documentation would be very helpful, thanks, great job on FCSWatch. 💯

**Comment by humhei** [comment]
Thanks.
I will read that thread and answer you

**Comment by humhei** [comment]
## FcsWatch.Core
The core library (Include a lots of common logic 
e.g `project cracker`, `file watcher`, mailbox group for concurrrent, and so on )

## FcsWatch.Binary (Ref FcsWatch.Core)
 It compile fsharp codes to .dll and .pdb (binary)
**No** webhoook currrently supported(No reason to send a dll and pdb)
Because it stop the whole application and replace the `.dll` and `.pdb` and then rerun application (This will make application debuggable and cross-projects compiling) 

## FcsWatch-Porta (Ref FcsWatch.Core)
It is  ported from (FSharp.Compiler.PortaCode)[https://github.com/fsprojects/FSharp.Compiler.PortaCode]

It sends a webhook to the host program
And then, the host program can replace its logic

**Comment by tylerhartwig** [comment]
Ah okay, I was hoping FcsWatch.Binary would support webhooks. 

In my case I'm trying to implement a stateful-hot reload and wanting to use FCSWatch to watch and compile the files quickly. I currently set up a watch on the resulting binary directory to manually send over the files. A webhook however, would probably be more convenient as sometimes I get Bad IL Format exceptions with my current method.

**Comment by humhei** [comment]
What's the meaning of stateful-hot 
On watcher side or Program side?
Are you trying somthing like time-level debugging?

**Comment by tylerhartwig** [comment]
On the program side I'm going to keep the program in its current state. In this case it is Elmish and I will be maintaining the model on update. 

FCSWatch works great on Bolero, but I'm hoping for a live-reload, rather than having to refresh the page. What I'm lacking is a good hook or way to monitor when the updated dlls are ready to read and send over.

**Comment by humhei** [comment]
I get your point, And will try to fix it

**Comment by tylerhartwig** [comment]
Thanks, looking forward to it, this tool is very useful.

**Comment by humhei** [comment]
May be fixed, Released as 0.7.3

**Comment by humhei** [comment]
Doc also has been updated

**Comment by tylerhartwig** [comment]
Awesome, that was an extremely fast turn around.
Just to be clear, the webhook for `dll`s then only indicate when the job is done, and does **not** send the files?

That's perfect for my use case, just want to confirm. 

Thanks so much 👍

**Comment by humhei** [comment]
`FcsWatch.Binary` will try to rerun the program,
Which means it will stop host program first,
A stopped program may not be able to receive the webhook

**Comment by tylerhartwig** [comment]
Yes, this makes sense, is there now a webhook for binary though?

And the webhook indicates when the compilation has finished?

**Comment by humhei** [comment]
> And the webhook indicates when the compilation has finished?

Yes, Only send a webhook to indicates when the compilation has finished(rerun or run)

**Comment by tylerhartwig** [comment]
Perfect, thank you so much 👍

**Comment by tylerhartwig** [comment]
One additional thought, as a further improvement.
In addition to sending whether this is a "Run" or "Rerun" just sending the _names_ of the changed files could prove useful. 

Very excited to start using this.

**Comment by humhei** [comment]
OK... will try to fix it next time.

You can also send a Pull request

**Comment by humhei** [comment]
https://github.com/humhei/FCSWatch/blob/master/src/FcsWatch.Binary/AutoReload.fs#L19
```
[<RequireQualifiedAccess>]
type WhyRun =
    | Rerun
    | Run
```
to 
```
[<RequireQualifiedAccess>]
type WhyRun =
    | Rerun of fileChanges: string list
    | Run 
```

**Comment by tylerhartwig** [comment]
Yes, I will explore this further and open a PR, thank you.

**Comment by humhei** [comment]
https://github.com/humhei/FCSWatch/blob/master/src/FcsWatch.Core/Types.fs#L557
```fsharp
[<RequireQualifiedAccess>]
type WhyCompile =
    | WarmCompile
    | DetectFileChange
```
to 
```fsharp
[<RequireQualifiedAccess>]
type WhyCompile =
    | WarmCompile
    | DetectFileChange of filechanges
```
https://github.com/humhei/FCSWatch/blob/master/src/FcsWatch.Binary/AutoReload.fs#L168
Then you can resolve Why compile in lasttasks
