### ISSUE TITLE
Add support for tracking content files

### ISSUE THREAD

**Issue by tylerhartwig** [humhei/FCSWatch#35]
Adding support for tracking content files can be important for Type Providers. 

In my use case, Bolero has an HTML Type Provider, when I make a change to an HTML file, I would like a re-compilation to occur. 

Should this be a toggle via a switch? 

Willing to contribute this, just checking in on direction.

**Comment by humhei** [comment]
https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/dotnet-watch.md#customize-files-list-to-watch

By default 
FcsWatch doesn't watch html files.

Do you need to implement this feature to watch addtional files?

**Comment by tylerhartwig** [comment]
Yes, that would work.

Is that how it should operate?
