### ISSUE TITLE
How to do a hot reload?

### ISSUE THREAD

**Issue by 7sharp9** [humhei/FCSWatch#37]
I looked at the readme but its not immediately obvious how to do hot reloading?

**Comment by humhei** [comment]
https://github.com/humhei/FCSWatch#from-cli


> dotnet tool install --global fcswatch-cli
> 
> fcswatch --project-file yourProjectFile
> 
> FcsWatch will load your project in autoReload mode by defalut


Does `fcswatch --project-file yourProjectFile(end with .fsproj... Also should be a executable project) ` worked for you?

**Comment by 7sharp9** [comment]
I mean how to get interpreted code to be reloaded?

**Comment by humhei** [comment]
Maybe you want
https://www.nuget.org/packages/fslive-cli-test/
It is almost the same to https://github.com/fsprojects/FSharp.Compiler.PortaCode

It have not been documented....

Actually, When @dsyme think we should merge FcsWatch and FSharp.Compiler.PortaCode together

I abstract all the common codes to `FcsWatch.Core`

This means `FSharp.Compiler.PortaCode` can get benifit from cross-projects compiling and multiple target framework project(Though i don't test it, it may not get worked, As FcsWatch.Binary is all ok for me)

**Comment by 7sharp9** [comment]
Thanks @humhei What I really wanted whether binary or interpreted was to keep the model between reloads, so the binary would be swapped but the model would remain the same.

**Comment by humhei** [comment]
IMHO.
Maybe implement [akka.Persistance](https://github.com/humhei/Akka.Persistence.LiteDB.FSharp) in your program side should be a good way?

**Comment by 7sharp9** [comment]
@humhei So is there a webhook listener defined in this repo that I missed or is that only in fabulous?

**Comment by humhei** [comment]
### For  interpreted code （fslive cli）
It has the same effect when comparing to [FSharp.Compiler.PortaCode](https://github.com/fsprojects/FSharp.Compiler.PortaCode)

The watcher host will try to send serialized code check results AST to the program side(Not limited to fabulous)

### For  binary mode （fcswatcher cli）

The watcher host will only send a webhook (only contains dll file which was swapped #21 ) when we rerun program 

It is only a notification but doesn't make more sense,
As rerun means that it will try to stop program first,And then run it



If you don't want to loose model  after reload,
You can  save your model to database(For me, It's Akka.Persistence)
And then when program is reloaded,
You can load your model from database 
(I didn't test it)

**Comment by 7sharp9** [comment]
Yeah I know this, the point I was trying to make is there is no example of client socket code to demonstrate the interpreted mode, you have to look in fabulous to find an example of that.

**Comment by 7sharp9** [comment]
Examples of both parts you described above would be good especially the persistence of the model you described.  

So on a binary web hook notification you get a notification when a dll is about to be swapped so you can persist the model?

On a rerun is there also a notification so you can load a model on startup?

**Comment by humhei** [comment]
In **binary** reload mode.
If you use the way i described above to persistent model to database in program side,
You don't need to catch the webhook,

As akka.persistence will load (whether from snapshot or journal) your model from database after rerunning program automatically

The only thing you should do is that after everytime model is changed 
You should persistent them to database..


Also, I am worried about that if your model can be serializable or not

**Comment by humhei** [comment]
Sorry I didn't test it,
It's only just an idea

**Comment by 7sharp9** [comment]
Theres also the issue of if you change the models shape in-between restarts.
